version: 1.0.0.{build}

install:
 - appveyor DownloadFile https://www.cygwin.com/setup-x86_64.exe -FileName C:\cygwin64\setup-x86_64.exe
 - C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P clang

build_script:
 - C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/lsync CC=clang"
