version: 1.0.0.{build}

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
 - C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/lsync"
