version: 1.0.0.{build}

build_script:
 - C:\cygwin64\bin\bash -lc "make -C /cygdrive/c/projects/lsync"

on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
