version: 1.0.0.{build}

configuration:
 - Release

platform:
 - Win32
 - x64

image:
 - Visual Studio 2017
 - Visual Studio 2015
 - Visual Studio 2013
 - Visual Studio 2012
 - Visual Studio 2010

build:
 project: vs2010.sln
 verbosity: minimal
 parallel: true

matrix:
 exclude:
  - image: Visual Studio 2010
  - image: Visual Studio 2017
